"""Update models with Employee and manager relationship

Revision ID: 4b6f9b1f9be6
Revises: fcdff47ff2ec
Create Date: 2024-12-12 20:13:12.568645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6f9b1f9be6'
down_revision: Union[str, None] = 'fcdff47ff2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.add_column('influencers', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'influencers', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'influencers', type_='foreignkey')
    op.drop_column('influencers', 'manager_id')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
